# Nome da aplicação
spring.application.name=ChatbotDocker2

# Configurações do banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/chatbotDB
spring.datasource.username=root
spring.datasource.password=luca##12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
python.api.url=http://localhost:5000/api